# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c13200e9bdcf94efd3828604957e1ef83122e9c8e219e3c9cda93d4f4290f40d308ea2202811bedc358012504c0fa2345e1235078f6e890bf148d844ba332af

test:
  secret_key_base: d5ba1a55cc25fd1336b5b06e3e5978206ff7cb3b5a2a6057f2ac12ed5eb85f9cb30e2e4c0a0a5f572c6a50d7ef9af982cc702e642972b7fb6bd6b7d98d42dd7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
